language: R
r:
  - bioc-devel
  - bioc-release
sudo: false
cache: packages

r_build_args: --no-build-vignettes --no-manual --resave-data
r_check_args: --no-build-vignettes --no-manual

r-packages:
  - GSA

after_success:
  - Rscript -e 'covr::codecov()'